# =================================================================
# BASE DE CONOCIMIENTO DEL AGENTE TAOISTA - MASTER FILE
# =================================================================

# 1. DATOS DE ENTRENAMIENTO
# -----------------------------------------------------------------
datos = [
    # --- TRISTEZA ---
    ("Me siento muy triste y sin esperanza", "tristeza"),
    ("Siento que nada tiene sentido, estoy vacío", "tristeza"),
    ("Siento un vacío enorme que no puedo llenar con nada", "tristeza"),
    ("Hoy me levanté sin ganas de existir", "tristeza"),
    ("Todo lo que toco parece romperse", "tristeza"),
    ("Extraño tiempos mejores y me duele el pecho", "tristeza"),
    ("Nadie me entiende, estoy completamente solo", "tristeza"),
    ("La melancolía me atrapó esta tarde", "tristeza"),
    ("He llorado sin razón aparente", "tristeza"),
    ("Siento que estoy sobrando en este mundo", "tristeza"),
    ("Mi corazón está roto en mil pedazos", "tristeza"),
    ("No encuentro consuelo en ninguna parte", "tristeza"),
    ("Me duele mucho ver fotos viejas y recordar lo que perdí", "tristeza"),
    ("Siento que nadie nota si estoy o no estoy", "tristeza"),
    ("La soledad en esta casa se siente insoportable hoy", "tristeza"),
    ("He perdido la motivación para seguir mis sueños", "tristeza"),
    ("Siento que fallé y no hay vuelta atrás", "tristeza"),
    ("Cada día se siente igual de gris y pesado", "tristeza"),
    ("Extraño a alguien que ya no va a volver", "tristeza"),
    ("Tengo un dolor en el alma que no sé explicar", "tristeza"),
    ("A veces desearía simplemente desaparecer un rato", "tristeza"),
    ("Me siento desconectado de todos mis amigos", "tristeza"),
    ("Me siento de la verga hoy", "tristeza"),
    ("Todo me sale de la chingada", "tristeza"),
    ("Ando bien agüitado, no quiero nada", "tristeza"),
    ("La neta me siento dlv (de la verga)", "tristeza"),
    ("Siento que valgo madre en la vida", "tristeza"),
    ("Me lleva la que me trajo, qué tristeza", "tristeza"),
    ("Ando bajoneado, todo está pinche gris", "tristeza"),
    ("Me siento culero, la verdad", "tristeza"),
    ("Siento un hueco bien cabrón en el pecho", "tristeza"),
    ("La vida me está tratando de la patada", "tristeza"),
    ("Ella me dejó y no sé cómo seguir", "tristeza"),
    ("Terminé con mi pareja y me siento vacío", "tristeza"),
    ("Extraño sus mensajes de buenos días", "tristeza"),
    ("Siento que perdí al amor de mi vida", "tristeza"),
    ("Verla con otro me destroza el alma", "tristeza"),
    ("Me duele pensar que ya no somos nada", "tristeza"),
    ("Nuestro aniversario ya no significa nada", "tristeza"),
    ("Tengo el corazón hecho pedazos por su culpa", "tristeza"),
    ("Ya no creo en el amor, me rindo", "tristeza"),
    ("Me siento usado y desechado", "tristeza"),
    ("Me siento fatal por lo que dije ayer", "tristeza"),
    ("La cagué horrible y no sé cómo arreglarlo", "tristeza"),
    ("Me arrepiento de no haber estado ahí", "tristeza"),
    ("Siento que soy una mala persona", "tristeza"),
    ("No me perdono haberle fallado así", "tristeza"),
    ("Cargo con una culpa que no me deja vivir", "tristeza"),
    ("Ojalá pudiera regresar el tiempo y cambiarlo", "tristeza"),
    ("Me siento sucio por lo que hice", "tristeza"),
    ("Falleció alguien muy importante para mí y no lo acepto", "tristeza"),
    ("Extraño demasiado a mi abuela, me hace mucha falta", "tristeza"),
    ("Perdí a mi mascota y la casa se siente vacía", "tristeza"),
    ("El luto me está consumiendo por dentro", "tristeza"),
    ("Siento que una parte de mí murió con él", "tristeza"),
    ("Ya no puedo llamar a mis padres y eso me mata", "tristeza"),
    ("La muerte es injusta, se llevó a quien más amaba", "tristeza"),
    ("No pude despedirme y cargo con ese dolor", "tristeza"),
    ("Ver su silla vacía me rompe el corazón cada día", "tristeza"),

    # --- ANSIEDAD ---
    ("Tengo mucha ansiedad y miedo por el futuro", "ansiedad"),
    ("Estoy inquieto, no puedo dejar de pensar", "ansiedad"),
    ("Tengo un nudo en el estómago que no se quita", "ansiedad"),
    ("Siento que algo malo va a pasar pronto", "ansiedad"),
    ("No puedo dejar de mover la pierna, estoy muy nervioso", "ansiedad"),
    ("Me estoy ahogando en mis propios pensamientos", "ansiedad"),
    ("El futuro me aterra demasiado", "ansiedad"),
    ("Siento taquicardia y me falta el aire", "ansiedad"),
    ("¿Y si fallo? ¿Y si todos se burlan?", "ansiedad"),
    ("Mi mente va a mil por hora y no frena", "ansiedad"),
    ("Necesito controlar todo o me desespero", "ansiedad"),
    ("Siento que pierdo el control de mi vida", "ansiedad"),
    ("Siento que todos me miran y me juzgan cuando hablo", "ansiedad"),
    ("Tengo miedo de decir algo estúpido y arruinarlo todo", "ansiedad"),
    ("La presión del trabajo me está matando", "ansiedad"),
    ("No puedo dormir pensando en los pendientes de mañana", "ansiedad"),
    ("Siento que el tiempo se me acaba y no he hecho nada", "ansiedad"),
    ("Me da pánico recibir llamadas de números desconocidos", "ansiedad"),
    ("Siento una opresión en el pecho cuando pienso en dinero", "ansiedad"),
    ("Tengo miedo de enfermarme o que algo le pase a mi familia", "ansiedad"),
    ("No puedo quedarme quieto, necesito hacer algo ya", "ansiedad"),
    ("Me siento atrapado y sin salida en esta situación", "ansiedad"),
    ("Me estoy malviajando bien feo", "ansiedad"),
    ("Siento que me va a dar el patatús", "ansiedad"),
    ("Ando bien paniqueado por lo que pasó", "ansiedad"),
    ("Siento la cabeza hecha un desmadre", "ansiedad"),
    ("Me siento bien pinche nervioso sin razón", "ansiedad"),
    ("Traigo un nudo culero en la garganta", "ansiedad"),
    ("Me está cargando el payaso con tanta presión", "ansiedad"),
    ("No puedo ni tragar del pinche estrés", "ansiedad"),
    ("Siento que voy a valer madre en el examen", "ansiedad"),
    ("Me siento asfixiado, está cabrón", "ansiedad"),
    ("Siento que soy un fraude y se van a dar cuenta", "ansiedad"),
    ("Me da pánico que descubran que no sé nada", "ansiedad"),
    ("Siento que no merezco estar aquí", "ansiedad"),
    ("Tengo miedo de no estar a la altura", "ansiedad"),
    ("Me comparo con todos y siempre pierdo", "ansiedad"),
    ("Me aterra hablar en público, me bloqueo", "ansiedad"),
    ("Siento que todos se ríen de mí a mis espaldas", "ansiedad"),
    ("Tengo miedo de quedarme pobre", "ansiedad"),
    ("Las redes sociales me hacen sentir miserable e insuficiente", "ansiedad"),
    ("No puedo dejar de ver noticias horribles y me paniqueo", "ansiedad"),
    ("Siento que todos tienen vidas perfectas en Instagram menos yo", "ansiedad"),
    ("El celular no para de sonar y me pone de nervios", "ansiedad"),
    ("Necesito desconectarme pero tengo miedo de perderme algo", "ansiedad"),
    ("Tengo el cerebro frito de tanta información inútil", "ansiedad"),
    ("Me comparo con gente de internet y me siento basura", "ansiedad"),
    ("La tecnología me está robando la vida real", "ansiedad"),

    # --- CALMA ---
    ("Estoy en paz, todo fluye bien", "calma"),
    ("Me siento agradecido con la vida", "calma"),
    ("Hoy el aire se siente más ligero", "calma"),
    ("Disfruto del silencio de mi habitación", "calma"),
    ("Me siento en sintonía con el universo", "calma"),
    ("Agradezco estar vivo un día más", "calma"),
    ("Todo está justo donde debe estar", "calma"),
    ("Me tomé un té y me siento renovado", "calma"),
    ("No necesito nada más para ser feliz ahora", "calma"),
    ("Observar las nubes me trajo mucha paz", "calma"),
    ("Siento una tranquilidad profunda en mi ser", "calma"),
    ("He aceptado las cosas que no puedo cambiar", "calma"),
    ("El sonido de la lluvia me hace sentir muy tranquilo", "calma"),
    ("Hoy decido no preocuparme por lo que no puedo controlar", "calma"),
    ("Me siento ligero, como si me hubiera quitado un peso de encima", "calma"),
    ("Disfruto simplemente estando aquí y ahora", "calma"),
    ("He perdonado y me siento libre", "calma"),
    ("La brisa fresca en mi cara me reconforta", "calma"),
    ("No tengo prisa, llegaré cuando tenga que llegar", "calma"),
    ("Siento una calidez agradable en mi interior", "calma"),
    ("Todo tiene su momento bajo el sol", "calma"),
    ("Estoy agradecido por las pequeñas cosas de hoy", "calma"),
    ("Siento que hoy empieza un nuevo capítulo en mi vida", "calma"),
    ("Después de la tormenta, por fin veo la luz", "calma"),
    ("Me siento listo para volver a intentarlo con calma", "calma"),
    ("He limpiado mi espacio y mi mente se siente clara", "calma"),
    ("Tengo esperanza de que todo se acomodará", "calma"),
    ("Me siento fresco y con energía renovada", "calma"),
    ("He soltado lo viejo para dejar entrar lo nuevo", "calma"),

    # --- IRA ---
    ("Tengo mucha ira, estoy enojado con todos", "ira"),
    ("Odio que las cosas no salgan como quiero", "ira"),
    ("Estoy harto de que me digan qué hacer", "ira"),
    ("Quiero gritar hasta quedarme sin voz", "ira"),
    ("Me revienta que la gente sea tan hipócrita", "ira"),
    ("Todo me sale mal, maldita sea", "ira"),
    ("No soporto ver a nadie hoy", "ira"),
    ("Me hierve la sangre cuando veo injusticias", "ira"),
    ("Tengo ganas de golpear la pared", "ira"),
    ("Estoy furioso conmigo mismo por ser así", "ira"),
    ("Odio sentirme tan impotente", "ira"),
    ("La estupidez humana me tiene cansado", "ira"),
    ("Mi jefe no valora mi esfuerzo y eso me enfurece", "ira"),
    ("Me robaron el crédito por algo que yo hice", "ira"),
    ("Odio tener que repetir las cosas mil veces", "ira"),
    ("Es injusto que siempre ganen los mentirosos", "ira"),
    ("Me da mucha rabia el tráfico y perder mi tiempo", "ira"),
    ("No soporto que me interrumpan cuando estoy hablando", "ira"),
    ("Me siento traicionado por alguien en quien confiaba", "ira"),
    ("Tengo ganas de mandarlo todo al diablo", "ira"),
    ("Estoy cansado de ser siempre el que cede", "ira"),
    ("La incompetencia de los demás me saca de quicio", "ira"),
    ("Estoy emputado con todo el mundo", "ira"),
    ("Me tienen hasta la madre con sus pendejadas", "ira"),
    ("Me caga que no me salgan las cosas", "ira"),
    ("Chinga su madre, ya no aguanto más", "ira"),
    ("Qué pinche coraje tengo atorado", "ira"),
    ("Me reencabrona la gente mentirosa", "ira"),
    ("Tengo ganas de mandar todo a la goma", "ira"),
    ("Me hierve la sangre, no mames", "ira"),
    ("Estoy que me lleva la chingada del coraje", "ira"),
    ("Pinche día asqueroso que llevo", "ira"),
    ("Me caga que a él le vaya bien y a mí no", "ira"),
    ("Es injusto que ella tenga todo tan fácil", "ira"),
    ("Me da rabia verlos felices mientras yo sufro", "ira"),
    ("Odio que siempre lo prefieran a él", "ira"),
    ("Me revienta que presuma su dinero", "ira"),
    ("¿Por qué la vida le sonríe a los idiotas?", "ira"),
    ("Me dan celos enfermizos cuando sale", "ira"),
    ("Me molesta que nadie reconozca mi talento", "ira"),
    ("Maldita sea mi suerte comparada con la suya", "ira"),
    ("Me apuñalaron por la espalda quienes decían ser mis amigos", "ira"),
    ("Descubrí que me estuvieron mintiendo todo este tiempo", "ira"),
    ("Me usaron para conseguir lo que querían y luego me botaron", "ira"),
    ("Odio a la gente doble cara, son unos hipócritas", "ira"),
    ("Le conté mi secreto y se lo dijo a todos", "ira"),
    ("Confié ciegamente y me vieron la cara de idiota", "ira"),
    ("No perdono la deslealtad, eso no se olvida", "ira"),
    ("Me da coraje haber sido tan ingenuo con esa persona", "ira"),

    # --- CONFUSIÓN ---
    ("No sé qué camino tomar", "confusion"),
    ("Me siento perdido, no sé quién soy", "confusion"),
    ("No sé si tomé la decisión correcta", "confusion"),
    ("Me siento perdido en un laberinto", "confusion"),
    ("Tengo tantas opciones que me bloqueo", "confusion"),
    ("No entiendo qué esperan de mí", "confusion"),
    ("Todo es muy borroso en mi mente ahora", "confusion"),
    ("¿Quién soy realmente?", "confusion"),
    ("Siento que camino sin rumbo fijo", "confusion"),
    ("Mis pensamientos se contradicen todo el tiempo", "confusion"),
    ("No entiendo por qué la gente actúa como actúa", "confusion"),
    ("Siento que todo lo que creía saber es mentira", "confusion"),
    ("No sé si debo seguir luchando o rendirme", "confusion"),
    ("Mi cabeza es un caos de ideas contradictorias", "confusion"),
    ("¿Cuál es el propósito de todo esto?", "confusion"),
    ("Me siento dividido entre dos caminos", "confusion"),
    ("No logro ver con claridad mi futuro", "confusion"),
    ("Tengo preguntas que nadie sabe responderme", "confusion"),
    ("No sé qué pedo con mi vida", "confusion"),
    ("Ando bien norteado, no sé pa dónde darle", "confusion"),
    ("No entiendo ni madres de lo que pasa", "confusion"),
    ("Me siento sacado de onda", "confusion"),
    ("Qué pedo, todo cambió de repente", "confusion"),
    ("No sé si cagarla o quedarme quieto", "confusion"),

    # --- CANSANCIO ---
    ("Estoy agotado, no tengo energía", "cansancio"),
    ("Trabajo demasiado y no descanso", "cansancio"),
    ("Me siento drenado por completo", "cansancio"),
    ("Necesito dormir mil años", "cansancio"),
    ("Estoy hasta el huevo de trabajar", "cansancio"),
    ("Ya no jalo, necesito dormir una semana", "cansancio"),
    ("Ando bien madreado, me duele todo", "cansancio"),
    ("Me siento hecho mierda físicamente", "cansancio"),
    ("Ya dio lo que tenía que dar, estoy fundido", "cansancio"),
    ("Estoy molido, ya no doy una", "cansancio"),
    ("Me siento como trapo viejo, bien gastado", "cansancio"),
    ("La neta ya no tengo pila para nada", "cansancio"),
    ("Estoy que me caigo de sueño, al chile", "cansancio"),
    ("Qué hueva de vida, estoy agotadísimo", "cansancio"),
    ("Todo me da igual, me importa un carajo", "cansancio"),
    ("No tengo ganas ni de levantarme a comer", "cansancio"),
    ("La vida me sabe a cartón, no disfruto nada", "cansancio"),
    ("Hago las cosas por inercia, soy un robot", "cansancio"),
    ("Me da hueva hasta hablar con mis amigos", "cansancio"),
    ("Simplemente no le veo el punto a esforzarme", "cansancio"),
    ("Estoy en piloto automático todo el día", "cansancio"),
    ("Me siento gris, ni feliz ni triste, solo apagado", "cansancio"),
    ("Tengo la mente en blanco, no se me ocurre nada", "cansancio"),
    ("Me siento estancado, como si no avanzara nada", "cansancio"),
    ("Estoy bloqueado, intento trabajar y no puedo", "cansancio"),
    ("Mi creatividad se murió, estoy seco", "cansancio"),
    ("Forzarme a pensar me duele físicamente", "cansancio"),
    ("Necesito vacaciones de mi propio cerebro", "cansancio"),
    
    # --- NUEVA EMOCIÓN: MIEDO (Lote 1) ---
    ("Tengo mucho miedo y no sé por qué", "miedo"),
    ("Estoy aterrorizado con lo que pueda pasar", "miedo"),
    ("Siento un pánico profundo que me paraliza", "miedo"),
    ("Me da pavor intentarlo y fallar", "miedo"),
    ("Estoy temblando de miedo ahora mismo", "miedo"),
    ("Siento que el corazón se me va a salir del susto", "miedo"),
    ("Tengo miedo de morir solo", "miedo"),
    ("Me aterra la oscuridad y el silencio", "miedo"),
    ("Siento que algo malo me está acechando", "miedo"),
    ("No puedo moverme, el miedo me tiene congelado", "miedo"),
    ("Me da mucho miedo perder a mi familia", "miedo"),
    ("Estoy cagado de miedo, la verdad", "miedo"),
    ("Siento horror al pensar en el futuro", "miedo"),
    ("Tengo miedo de que me lastimen", "miedo"),
    ("Me da pánico salir a la calle", "miedo"),
    ("Siento escalofríos de puro terror", "miedo"),
    ("Tengo miedo de las consecuencias", "miedo"),
    ("Me aterra la idea de quedarme sin nada", "miedo"),
    ("Estoy espantado con esa noticia", "miedo"),
    ("Me da miedo no ser suficiente", "miedo"),
    ("Siento que estoy en peligro inminente", "miedo"),
    ("Tengo miedo de enfermarme gravemente", "miedo"),
    ("Me da terror hablar en público", "miedo"),
    ("Estoy paniqueado, no sé qué hacer", "miedo"),
    ("Me da culo enfrentarme a él", "miedo"),
    ("Se me frunció del susto", "miedo"),
    ("Ando con el Jesús en la boca de puro miedo", "miedo"),
    ("Le saco a esa situación, me da mala espina", "miedo"),
    ("Me da zacate meterme en problemas", "miedo"),
    ("Tengo un miedo irracional a las alturas", "miedo"),
    ("Me aterra que descubran mi secreto", "miedo"),
    ("Siento que voy a perder el control del miedo", "miedo"),
    ("Tengo miedo de los cambios", "miedo"),
    ("Me da pavor la soledad eterna", "miedo"),
    ("Estoy muerto de miedo", "miedo"),
    ("Me da miedo confiar y que me traicionen", "miedo"),
    ("Siento un hueco en el estómago por el miedo", "miedo"),
    ("Tengo miedo de que todo sea una mentira", "miedo"),
    ("Me aterra la vejez y el olvido", "miedo"),
    ("Estoy asustadísimo, ayúdame", "miedo"),
    ("Me da meyo entrar ahí", "miedo"),
    ("Tengo miedo de no poder pagar mis deudas", "miedo"),
    ("Siento que el mundo es un lugar aterrador", "miedo"),
    ("Me da pánico que se burlen de mí", "miedo"),
    ("Tengo miedo de tomar la decisión equivocada", "miedo"),
    ("Me aterra ver sangre o accidentes", "miedo"),
    ("Siento que me persiguen, tengo miedo", "miedo"),
    ("Tengo miedo de despertar y que no estés", "miedo"),
    ("Me da horror pensar en la guerra", "miedo"),
    ("Estoy frikeado, me da mucho miedo esto", "miedo"),
    ("Siento que mis peores pesadillas se cumplen", "miedo"),
    ("Tengo miedo de no volver a ser feliz", "miedo"),
    ("Me aterra el rechazo social", "miedo"),
    ("Siento que soy un cobarde, tengo mucho miedo", "miedo"),
    ("Me da miedo hasta mi propia sombra hoy", "miedo"),
    
    # --- NUEVA EMOCIÓN: SOLEDAD (Lote 2) ---
    ("Me siento completamente solo en este mundo", "soledad"),
    ("No tengo a nadie con quien hablar de verdad", "soledad"),
    ("Siento que a nadie le importo, soy invisible", "soledad"),
    ("La casa está vacía y el silencio me aplasta", "soledad"),
    ("Estoy rodeado de gente pero me siento solo", "soledad"),
    ("Nadie me entiende, es como si hablara otro idioma", "soledad"),
    ("Extraño tener compañía, alguien que me abrace", "soledad"),
    ("Siento un aislamiento profundo, como una isla", "soledad"),
    ("Me duele no recibir ni un mensaje en todo el día", "soledad"),
    ("Todos tienen planes menos yo", "soledad"),
    ("Me siento abandonado por mis amigos", "soledad"),
    ("La soledad me está consumiendo poco a poco", "soledad"),
    ("No tengo a quién llamar cuando estoy mal", "soledad"),
    ("Siento que camino solo por la vida", "soledad"),
    ("Me pesa mucho cenar solo todas las noches", "soledad"),
    ("Nadie se acuerda de mí si yo no los busco", "soledad"),
    ("Siento que no encajo en ningún lado", "soledad"),
    ("La soledad es fría y oscura", "soledad"),
    ("Me siento desamparado y sin apoyo", "soledad"),
    ("A veces hablo solo para escuchar una voz", "soledad"),
    ("Siento que mi presencia no hace diferencia", "soledad"),
    ("Me dejaron solo cuando más los necesitaba", "soledad"),
    ("Siento que soy el único que no tiene pareja", "soledad"),
    ("La soledad me hace sentir defectuoso", "soledad"),
    ("Nadie nota mi ausencia", "soledad"),
    ("Me siento excluido de todo", "soledad"),
    ("Siento que moriré solo y nadie se enterará", "soledad"),
    ("La noche es el peor momento, me siento muy solo", "soledad"),
    ("Quisiera tener a alguien que me escuche sin juzgar", "soledad"),
    ("Me siento como un fantasma entre los vivos", "soledad"),
    ("Todos hacen su vida y yo me quedo atrás, solo", "soledad"),
    ("Siento que no pertenezco a ninguna manada", "soledad"),
    ("La soledad me duele físicamente en el pecho", "soledad"),
    ("Me siento solo incluso con mi familia", "soledad"),
    ("Nadie me pregunta cómo estoy realmente", "soledad"),
    ("Siento que estoy gritando en el vacío", "soledad"),
    ("Me da tristeza ver grupos de amigos y yo estar solo", "soledad"),
    ("Siento que nadie me conoce de verdad", "soledad"),
    ("La soledad se ha vuelto mi única compañera", "soledad"),
    ("Me siento marginado y olvidado", "soledad"),
    ("No tengo con quién compartir mis logros", "soledad"),
    ("Siento que sobro en todas partes", "soledad"),
    ("Me siento solo como un perro", "soledad"),
    ("Nadie me espera en casa", "soledad"),
    ("Siento que perdí la conexión con los demás", "soledad"),
    ("Me siento solo en la multitud", "soledad"),
    ("La soledad me hace pensar cosas feas", "soledad"),
    ("No tengo hombro donde llorar", "soledad"),
    ("Siento que todos me dieron la espalda", "soledad"),
    ("Me siento solo y triste, necesito un abrazo", "soledad"),
    ("La soledad es un desierto interminable", "soledad"),
    ("Siento que nadie me extraña", "soledad"),
    ("Me siento solo, abandonado a mi suerte", "soledad"),
    ("No hay nadie a mi lado en esta lucha", "soledad"),
    ("Siento que mi voz no llega a nadie", "soledad"),
    
    # --- NUEVA EMOCIÓN: ENVIDIA (Lote 3) ---
    ("Me muero de envidia cuando veo sus fotos de viaje", "envidia"),
    ("Odio que a él todo le salga bien y a mí no", "envidia"),
    ("Me da coraje que tenga más dinero que yo", "envidia"),
    ("Por qué ella es tan bonita y yo no", "envidia"),
    ("Siento celos de su éxito profesional", "envidia"),
    ("Me revienta que siempre sea el centro de atención", "envidia"),
    ("Desearía tener la suerte que tiene ese idiota", "envidia"),
    ("Me da rabia verlos tan felices juntos", "envidia"),
    ("No soporto que presuma sus cosas nuevas", "envidia"),
    ("Me siento inferior cuando me comparo con ellos", "envidia"),
    ("Qué injusto que a él le den el puesto y a mí no", "envidia"),
    ("Me arde la sangre ver que le va mejor que a mí", "envidia"),
    ("Siento envidia de la buena, pero me duele", "envidia"),
    ("Ojalá yo tuviera su vida perfecta", "envidia"),
    ("Me molesta que todos lo alaben tanto", "envidia"),
    ("Me siento un fracasado al ver sus logros", "envidia"),
    ("Por qué la vida es tan generosa con algunos y conmigo no", "envidia"),
    ("Me da envidia su coche nuevo", "envidia"),
    ("Me siento mal cuando veo que mis amigos avanzan y yo no", "envidia"),
    ("Me da pica que sea tan talentoso", "envidia"),
    ("Odio sentir esta envidia cochina", "envidia"),
    ("Quisiera que le fuera mal para no sentirme tan menos", "envidia"),
    ("Me da coraje que tenga todo tan fácil", "envidia"),
    ("Siento que no merezco menos que ella", "envidia"),
    ("Me da envidia su cuerpo, la neta", "envidia"),
    ("Me molesta su felicidad falsa", "envidia"),
    ("Siento que la vida me debe algo cuando los veo", "envidia"),
    ("Me da rabia que consiga todo sin esforzarse", "envidia"),
    ("No puedo alegrarme por su éxito, me siento mal", "envidia"),
    ("Me da envidia que viaje tanto", "envidia"),
    ("Siento que siempre estoy a la sombra de los demás", "envidia"),
    ("Me caga que tenga tanta suerte", "envidia"),
    ("Por qué a mí me cuesta tanto y a él nada", "envidia"),
    ("Me siento verde de envidia", "envidia"),
    ("Me da coraje que sus padres le den todo", "envidia"),
    ("Siento envidia de su relación perfecta", "envidia"),
    ("Me molesta que sea tan popular", "envidia"),
    ("Desearía tener su carisma", "envidia"),
    ("Me siento poca cosa a su lado", "envidia"),
    ("Me da envidia que no tenga preocupaciones", "envidia"),
    ("Odio que siempre gane", "envidia"),
    ("Me da rabia que tenga mejor sueldo que yo haciendo menos", "envidia"),
    ("Siento que el universo tiene favoritos y no soy yo", "envidia"),
    ("Me da envidia su casa tan grande", "envidia"),
    ("Me duele ver que otros cumplen mis sueños", "envidia"),
    ("Siento rencor porque a ella le va increíble", "envidia"),
    ("Me da envidia que sea tan inteligente", "envidia"),
    ("Me molesta ver sus historias de Instagram tan perfectas", "envidia"),
    ("Quisiera tener lo que él tiene", "envidia"),
    ("Me siento amargado por el éxito ajeno", "envidia"),
    ("Me da envidia su libertad", "envidia"),
    ("Siento que la vida es injusta repartiendo suerte", "envidia"),
    ("Me da coraje que le regalen todo", "envidia"),
    ("No soporto su sonrisa de triunfador", "envidia"),
    ("Me siento miserable comparando mi vida con la suya", "envidia"),
    
    # --- NUEVA EMOCIÓN: CULPA (Lote 4) ---
    ("Me siento muy culpable por lo que hice", "culpa"),
    ("No me perdono haberle hablado así", "culpa"),
    ("Siento que arruiné todo por mi estupidez", "culpa"),
    ("Me carcome la conciencia no haber estado ahí", "culpa"),
    ("Siento que soy una mala persona", "culpa"),
    ("Me arrepiento tanto de esa decisión", "culpa"),
    ("No puedo dormir pensando en mi error", "culpa"),
    ("Siento que le fallé a todos", "culpa"),
    ("Me duele haber lastimado a quien más quiero", "culpa"),
    ("Ojalá pudiera regresar el tiempo y no hacerlo", "culpa"),
    ("Me siento sucio por mis acciones", "culpa"),
    ("Cargo con una culpa que no me deja vivir en paz", "culpa"),
    ("Siento que no merezco ser feliz después de lo que hice", "culpa"),
    ("Me odio por haber sido tan egoísta", "culpa"),
    ("La culpa me está matando por dentro", "culpa"),
    ("Siento que debo pagar por mis errores", "culpa"),
    ("No sé cómo pedir perdón, me siento fatal", "culpa"),
    ("Me siento responsable de su sufrimiento", "culpa"),
    ("Fue mi culpa que todo saliera mal", "culpa"),
    ("Siento un peso enorme en el pecho por la culpa", "culpa"),
    ("Me avergüenza lo que hice, me siento culpable", "culpa"),
    ("No puedo mirarme al espejo sin sentir culpa", "culpa"),
    ("Siento que traicioné mis propios principios", "culpa"),
    ("Me siento culpable por no haber hecho más", "culpa"),
    ("La culpa no me deja disfrutar nada", "culpa"),
    ("Siento que soy un fraude y lastimo a la gente", "culpa"),
    ("Me siento culpable por sobrevivir y ellos no", "culpa"),
    ("Me duele haber desperdiciado esa oportunidad", "culpa"),
    ("Siento que decepcioné a mis padres", "culpa"),
    ("Me siento culpable por sentirme así", "culpa"),
    ("No puedo sacarme de la cabeza lo que pasó", "culpa"),
    ("Me siento culpable por gastar dinero en tonterías", "culpa"),
    ("Siento que todo es culpa mía, siempre", "culpa"),
    ("Me arrepiento de no haber dicho te quiero", "culpa"),
    ("Me siento culpable por ser feliz mientras otros sufren", "culpa"),
    ("Siento que merezco un castigo", "culpa"),
    ("Me siento culpable por haber mentido", "culpa"),
    ("La culpa es un veneno que me tragué", "culpa"),
    ("Siento que rompí algo que no se puede arreglar", "culpa"),
    ("Me siento culpable por alejarme de ellos", "culpa"),
    ("No me lo perdono, soy un idiota", "culpa"),
    ("Siento que manché mi reputación y me siento mal", "culpa"),
    ("Me siento culpable por no ser mejor", "culpa"),
    ("La culpa me persigue a donde voy", "culpa"),
    ("Siento que le robé tiempo a mi familia", "culpa"),
    ("Me siento culpable por comer eso", "culpa"),
    ("Siento remordimiento por mis palabras hirientes", "culpa"),
    ("Me siento culpable por no haber ayudado", "culpa"),
    ("Siento que soy una carga para los demás", "culpa"),
    ("Me siento culpable por priorizarme a mí mismo", "culpa"),
    ("La culpa no me deja avanzar", "culpa"),
    ("Siento que tengo una deuda impagable", "culpa"),
    ("Me siento culpable por olvidar esa fecha importante", "culpa"),
    ("Siento que no soy digno de perdón", "culpa"),
    
    # --- NUEVA EMOCIÓN: VERGÜENZA (Lote 5) ---
    ("Me siento muy avergonzado por lo que pasó", "verguenza"),
    ("Quisiera que la tierra me tragara ahora mismo", "verguenza"),
    ("No puedo ni levantar la cara de la pena", "verguenza"),
    ("Me siento humillado frente a todos", "verguenza"),
    ("Qué oso lo que hice, me quiero morir", "verguenza"),
    ("Siento que todos se burlan de mí a mis espaldas", "verguenza"),
    ("Me da mucha vergüenza mi cuerpo", "verguenza"),
    ("Siento que hice el ridículo total", "verguenza"),
    ("Me da pena hablar con gente nueva", "verguenza"),
    ("Siento vergüenza de mis orígenes", "verguenza"),
    ("Me puse rojo como un tomate, qué pena", "verguenza"),
    ("Siento que no estoy a la altura y me da vergüenza", "verguenza"),
    ("Me da vergüenza pedir ayuda", "verguenza"),
    ("Siento que soy la burla de la oficina", "verguenza"),
    ("Me da pena que me vean llorar", "verguenza"),
    ("Siento vergüenza ajena por lo que hizo él", "verguenza"),
    ("Me siento expuesto y vulnerable, qué vergüenza", "verguenza"),
    ("Me da vergüenza admitir que me equivoqué", "verguenza"),
    ("Siento que todos me juzgan por mi ropa", "verguenza"),
    ("Me da pena comer frente a otros", "verguenza"),
    ("Siento vergüenza de mi familia a veces", "verguenza"),
    ("Me siento estúpido por haber dicho eso", "verguenza"),
    ("Me da vergüenza que sepan mi secreto", "verguenza"),
    ("Siento que todos me miran con lástima", "verguenza"),
    ("Me da pena ajena esa situación", "verguenza"),
    ("Siento que perdí mi dignidad", "verguenza"),
    ("Me da vergüenza ser quien soy", "verguenza"),
    ("Siento que manché mi imagen pública", "verguenza"),
    ("Me da pena que me vean así de mal", "verguenza"),
    ("Siento vergüenza de mis fracasos", "verguenza"),
    ("Me da cosa que me escuchen cantar", "verguenza"),
    ("Siento que soy un bicho raro", "verguenza"),
    ("Me da vergüenza saludar a alguien que no me recuerda", "verguenza"),
    ("Siento que metí la pata hasta el fondo", "verguenza"),
    ("Me da pena preguntar en clase", "verguenza"),
    ("Siento que no encajo y me da vergüenza", "verguenza"),
    ("Me da vergüenza que vean mi casa", "verguenza"),
    ("Siento que todos son mejores que yo y me da pena", "verguenza"),
    ("Me da vergüenza mostrar mis sentimientos", "verguenza"),
    ("Siento que quedé como un tonto", "verguenza"),
    ("Me da pena que me inviten y no tener dinero", "verguenza"),
    ("Siento vergüenza de mi pasado", "verguenza"),
    ("Me da cosa que me vean en traje de baño", "verguenza"),
    ("Siento que todos notan mis defectos", "verguenza"),
    ("Me da vergüenza tropezarme en la calle", "verguenza"),
    ("Siento que soy indigno de atención", "verguenza"),
    ("Me da pena que me feliciten en público", "verguenza"),
    ("Siento que me puse en evidencia", "verguenza"),
    ("Me da vergüenza no saber la respuesta", "verguenza"),
    ("Siento que quiero desaparecer de la vergüenza", "verguenza"),
    ("Me da pena mi risa", "verguenza"),
    ("Siento que soy un desastre y me da pena", "verguenza"),
    ("Me da vergüenza que lean lo que escribo", "verguenza"),
    
    # --- NUEVA EMOCIÓN: SOBERBIA (Lote 6) ---
    ("Soy el mejor en lo que hago y nadie me llega", "soberbia"),
    ("Todos son unos idiotas comparados conmigo", "soberbia"),
    ("No necesito consejos de nadie, yo sé qué hacer", "soberbia"),
    ("Me merezco mucho más que esta gente mediocre", "soberbia"),
    ("Ellos deberían agradecerme que estoy aquí", "soberbia"),
    ("Nadie tiene mi nivel de inteligencia", "soberbia"),
    ("Yo nunca me equivoco, el error fue de ellos", "soberbia"),
    ("Me da flojera hablar con gente tan básica", "soberbia"),
    ("Soy superior a todos mis compañeros", "soberbia"),
    ("No tengo competencia, soy único", "soberbia"),
    ("Qué desperdicio que no me valoren como al rey que soy", "soberbia"),
    ("Mis ideas son brillantes, las de ellos son basura", "soberbia"),
    ("No me rebajo a discutir con ignorantes", "soberbia"),
    ("Yo nací para mandar, no para obedecer", "soberbia"),
    ("Nadie me puede enseñar nada nuevo", "soberbia"),
    ("Me siento un dios entre mortales", "soberbia"),
    ("Es obvio que tengo la razón, como siempre", "soberbia"),
    ("Me importa un carajo lo que piensen, soy mejor", "soberbia"),
    ("Ellos pierden si no me eligen", "soberbia"),
    ("Mi tiempo es demasiado valioso para esto", "soberbia"),
    ("Soy el único que sabe hacer las cosas bien aquí", "soberbia"),
    ("Me tienen envidia porque brillo demasiado", "soberbia"),
    ("No voy a pedir perdón, yo no fallé", "soberbia"),
    ("Me siento por encima de las reglas", "soberbia"),
    ("Qué difícil es estar rodeado de incompetentes", "soberbia"),
    ("Yo soy el premio, que se esfuercen ellos", "soberbia"),
    ("Nadie está a mi altura", "soberbia"),
    ("Soy indispensable, sin mí esto se cae", "soberbia"),
    ("Me da risa lo patéticos que son", "soberbia"),
    ("Yo no sigo tendencias, yo las creo", "soberbia"),
    ("Me merezco un trato especial porque soy especial", "soberbia"),
    ("No acepto críticas de quien no ha logrado nada", "soberbia"),
    ("Soy demasiado bueno para este trabajo", "soberbia"),
    ("Me siento el centro del universo", "soberbia"),
    ("Todos quieren ser yo", "soberbia"),
    ("Mi éxito es inevitable, soy un genio", "soberbia"),
    ("No me junto con perdedores", "soberbia"),
    ("Soy la perfección andando", "soberbia"),
    ("Me aburre la gente normal", "soberbia"),
    ("Yo dicto las reglas del juego", "soberbia"),
    ("Nadie me dice qué hacer", "soberbia"),
    ("Soy una leyenda viva", "soberbia"),
    ("Me siento intocable", "soberbia"),
    ("Mi talento es un regalo para el mundo", "soberbia"),
    ("No tengo rival", "soberbia"),
    ("Soy el más guapo y el más listo del cuarto", "soberbia"),
    ("Me resbala su opinión, yo sé quién soy", "soberbia"),
    ("Soy el alfa y ellos lo saben", "soberbia"),
    ("Me deben respeto por quien soy", "soberbia"),
    ("Yo brillo con luz propia", "soberbia"),
    ("Soy inalcanzable", "soberbia"),
    ("Me siento superior moralmente", "soberbia"),
    ("Yo no pido favores, yo los concedo", "soberbia"),
    
    # --- NUEVA EMOCIÓN: IMPACIENCIA (Lote 7) ---
    ("Ya me cansé de esperar, esto tarda años", "impaciencia"),
    ("Odio hacer filas, me desespera", "impaciencia"),
    ("Por qué todo es tan lento hoy", "impaciencia"),
    ("Necesito los resultados ya, no mañana", "impaciencia"),
    ("Me pone de malas que la gente camine lento", "impaciencia"),
    ("Ya vámonos, se nos hace tarde", "impaciencia"),
    ("No tengo tiempo para estas tonterías", "impaciencia"),
    ("Me urge que me contesten el mensaje", "impaciencia"),
    ("Qué desesperación con este tráfico", "impaciencia"),
    ("Quiero que pase rápido esta semana", "impaciencia"),
    ("Me revienta esperar a que cargue la página", "impaciencia"),
    ("Apúrate, no tengo todo el día", "impaciencia"),
    ("Siento que estoy perdiendo mi vida esperando", "impaciencia"),
    ("No soporto la incertidumbre, necesito saber ya", "impaciencia"),
    ("Me da ansiedad no ver avances rápido", "impaciencia"),
    ("Odio los comerciales, quiero ver el video ya", "impaciencia"),
    ("Por qué no pueden ser más eficientes", "impaciencia"),
    ("Me estoy comiendo las uñas de la desesperación", "impaciencia"),
    ("Ya quiero llegar, cuánto falta", "impaciencia"),
    ("Me molesta que den tantas vueltas para decir algo", "impaciencia"),
    ("Quiero saltarme todo este proceso aburrido", "impaciencia"),
    ("Me desespera la gente indecisa", "impaciencia"),
    ("No puedo quedarme quieto esperando", "impaciencia"),
    ("Siento que el tiempo no avanza", "impaciencia"),
    ("Me da coraje tener que esperar mi turno", "impaciencia"),
    ("Ya dámelo, no aguanto más", "impaciencia"),
    ("Me estresa que no lleguen a la hora", "impaciencia"),
    ("Quiero soluciones inmediatas", "impaciencia"),
    ("Me hierve la sangre cuando se tarda el mesero", "impaciencia"),
    ("No tengo paciencia para explicarlo dos veces", "impaciencia"),
    ("Me urge salir de aquí ya", "impaciencia"),
    ("Odio los trámites burocráticos lentos", "impaciencia"),
    ("Me siento atrapado cuando tengo que esperar", "impaciencia"),
    ("Por qué el semáforo no cambia, maldita sea", "impaciencia"),
    ("Me desespera no tener el control del tiempo", "impaciencia"),
    ("Quiero todo para ayer", "impaciencia"),
    ("Me pone nervioso esperar el diagnóstico", "impaciencia"),
    ("Ya cállate y ve al grano", "impaciencia"),
    ("Siento que exploto si tengo que esperar un minuto más", "impaciencia"),
    ("Me da ansiedad la lentitud del sistema", "impaciencia"),
    ("Quiero que sea viernes ya", "impaciencia"),
    ("Me molesta esperar a que se seque la pintura", "impaciencia"),
    ("No soporto ver la barrita de carga", "impaciencia"),
    ("Me urge que depositen ya", "impaciencia"),
    ("Me siento inquieto, quiero acción", "impaciencia"),
    ("Me desespera que no me entiendan rápido", "impaciencia"),
    ("Ya quiero ver el final, me salto las partes aburridas", "impaciencia"),
    ("Me da rabia perder tiempo en el transporte", "impaciencia"),
    ("No aguanto la espera telefónica con la musiquita", "impaciencia"),
    ("Me siento como león enjaulado esperando", "impaciencia"),
    ("Acelera, vas pisando huevos", "impaciencia"),
    ("Me desespera la calma de los demás", "impaciencia"),
    
    # --- NUEVA EMOCIÓN: FRUSTRACIÓN (Lote 8) ---
    ("Lo intento una y otra vez y no me sale", "frustracion"),
    ("Siento que estoy golpeando una pared de concreto", "frustracion"),
    ("Me da coraje que nada funcione como debería", "frustracion"),
    ("Estoy estancado en este problema y no veo la salida", "frustracion"),
    ("Por más que me esfuerzo, no avanzo nada", "frustracion"),
    ("Me siento inútil tratando de arreglar esto", "frustracion"),
    ("Quiero tirar la toalla, ya no puedo más", "frustracion"),
    ("Me frustra que no me entiendan cuando hablo", "frustracion"),
    ("Todo parece estar en mi contra hoy", "frustracion"),
    ("Siento que doy un paso adelante y dos atrás", "frustracion"),
    ("Me revienta que se trabe la computadora justo ahora", "frustracion"),
    ("No encuentro la solución y me desespera", "frustracion"),
    ("Siento que estoy perdiendo el tiempo intentando esto", "frustracion"),
    ("Me da rabia no tener las herramientas adecuadas", "frustracion"),
    ("Por qué es tan difícil hacer algo tan simple", "frustracion"),
    ("Me siento bloqueado mentalmente", "frustracion"),
    ("Odio cuando las cosas no salen como las planeé", "frustracion"),
    ("Me frustra depender de otros para avanzar", "frustracion"),
    ("Siento que nado contra la corriente", "frustracion"),
    ("Me dan ganas de romper todo de la impotencia", "frustracion"),
    ("Es imposible complacerlos, haga lo que haga", "frustracion"),
    ("Me siento atrapado en un callejón sin salida", "frustracion"),
    ("Me frustra no tener dinero para lo que necesito", "frustracion"),
    ("Siento que mi esfuerzo no vale para nada", "frustracion"),
    ("Me da coraje cometer el mismo error dos veces", "frustracion"),
    ("No veo resultados y eso me desmotiva", "frustracion"),
    ("Me siento limitado por cosas que no controlo", "frustracion"),
    ("Me frustra la burocracia inútil", "frustracion"),
    ("Siento que estoy hablando con la pared", "frustracion"),
    ("Me revienta que me cambien los planes a última hora", "frustracion"),
    ("No puedo creer que fallé en algo tan fácil", "frustracion"),
    ("Me siento impotente ante esta situación", "frustracion"),
    ("Me frustra no saber qué hacer con mi vida", "frustracion"),
    ("Siento que estoy desperdiciando mi talento", "frustracion"),
    ("Me da rabia que no reconozcan mi trabajo", "frustracion"),
    ("Ya probé todo y nada sirve", "frustracion"),
    ("Me siento saturado y sin opciones", "frustracion"),
    ("Me frustra ver tanta injusticia y no poder hacer nada", "frustracion"),
    ("Siento que el universo me está poniendo el pie", "frustracion"),
    ("Me da coraje no poder expresarme bien", "frustracion"),
    ("Me frustra ser tan perfeccionista y nunca terminar", "frustracion"),
    ("Siento que estoy en un ciclo sin fin", "frustracion"),
    ("Me revienta que me ignoren", "frustracion"),
    ("No soporto la incompetencia ajena que me afecta", "frustracion"),
    ("Me siento atado de manos", "frustracion"),
    ("Me frustra que el internet esté lento", "frustracion"),
    ("Siento que todo mi trabajo se fue a la basura", "frustracion"),
    ("Me da rabia no poder controlar mis emociones", "frustracion"),
    ("Me siento derrotado por este obstáculo", "frustracion"),
    ("Me frustra no encontrar lo que busco", "frustracion"),
    ("Siento que estoy gritando y nadie me oye", "frustracion"),
    ("Me da coraje que se rompa algo nuevo", "frustracion"),
    
    # --- NUEVA EMOCIÓN: RENCOR (Lote 9) ---
    ("No puedo olvidar lo que me hizo, jamás", "rencor"),
    ("Le guardo un rencor que no me deja vivir", "rencor"),
    ("Ojalá pague por todo el daño que causó", "rencor"),
    ("Nunca lo voy a perdonar, ni en mil años", "rencor"),
    ("Me hierve la sangre de solo escuchar su nombre", "rencor"),
    ("Siento odio cada vez que recuerdo ese día", "rencor"),
    ("La herida sigue abierta después de tanto tiempo", "rencor"),
    ("No merece ni un minuto de paz", "rencor"),
    ("Me duele recordar cómo me traicionó por la espalda", "rencor"),
    ("Es imposible borrar lo que pasó, eso no se olvida", "rencor"),
    ("Le deseo lo peor, la verdad, no puedo mentir", "rencor"),
    ("Me amarga la vida pensar en esa persona", "rencor"),
    ("No puedo soltar este odio que tengo atorado", "rencor"),
    ("Siento que me robó los mejores años de mi vida", "rencor"),
    ("Maldigo el día en que lo conocí", "rencor"),
    ("No hay perdón para gente tan miserable", "rencor"),
    ("Me da asco recordar su cara de hipócrita", "rencor"),
    ("Siento que tengo una espina clavada en el corazón", "rencor"),
    ("No puedo pasar página, me duele demasiado el orgullo", "rencor"),
    ("Me las va a pagar algún día, lo juro", "rencor"),
    ("Siento que se burló de mí y no lo supero", "rencor"),
    ("El rencor me está envenenando por dentro", "rencor"),
    ("No puedo ser amigo de alguien que me hizo eso", "rencor"),
    ("Me siento estúpido por haber confiado, y lo odio por eso", "rencor"),
    ("Cada vez que lo veo revivo todo el coraje", "rencor"),
    ("No se merece mi perdón ni mi lástima", "rencor"),
    ("Ojalá sufra lo mismo que yo sufrí", "rencor"),
    ("Tengo el corazón lleno de resentimiento", "rencor"),
    ("No puedo dejar ir el pasado, me persigue", "rencor"),
    ("Me da coraje que sea feliz después de lo que hizo", "rencor"),
    ("Siento que no hubo justicia para mí", "rencor"),
    ("Me trago mi coraje pero ahí sigue intacto", "rencor"),
    ("No puedo mirar a los ojos a quien me traicionó", "rencor"),
    ("Siento que me deben una disculpa que nunca llegará", "rencor"),
    ("Me pesa el odio que cargo todos los días", "rencor"),
    ("Yo no olvido, y mucho menos perdono", "rencor"),
    ("Me siento amargado por su culpa", "rencor"),
    ("Quisiera borrarlo de mi memoria pero el rencor no me deja", "rencor"),
    ("Siento que me arruinó la vida para siempre", "rencor"),
    ("No hay vuelta atrás después de una ofensa así", "rencor"),
    ("Me siento vengativo, quiero que le vaya mal", "rencor"),
    ("No puedo estar en paz sabiendo lo que hizo impunemente", "rencor"),
    ("Siento que se salió con la suya y me da rabia", "rencor"),
    ("El rencor es lo único que me queda de esa relación", "rencor"),
    ("Me da rabia haber sido tan bueno con quien no lo merecía", "rencor"),
    ("No puedo soltar, me aferro al dolor para no olvidar", "rencor"),
    ("Siento que me clavaron un puñal y lo dejaron ahí", "rencor"),
    ("Me da coraje recordar lo ingenuo que fui con él", "rencor"),
    ("No hay lugar en mi vida para el perdón", "rencor"),
    ("Siento un nudo en la garganta cuando hablan de ella", "rencor"),
    ("Me da asco su falsedad y no lo olvido", "rencor"),
    ("Me siento sucio de tanto odio que guardo", "rencor"),
    
    # --- NUEVA EMOCIÓN: CODICIA (Lote 10) ---
    ("Quiero más dinero, nunca es suficiente", "codicia"),
    ("Necesito comprarme ese coche nuevo como sea", "codicia"),
    ("Me siento pobre aunque tengo todo lo básico", "codicia"),
    ("No voy a descansar hasta ser millonario", "codicia"),
    ("Me obsesiona tener lo último en tecnología", "codicia"),
    ("Siento que valgo por lo que tengo en la cuenta", "codicia"),
    ("No puedo dejar de pensar en cómo ganar más", "codicia"),
    ("Me da miedo gastar y quedarme sin nada", "codicia"),
    ("Quiero el puesto de jefe por el sueldo, no por el trabajo", "codicia"),
    ("Envidio a los que tienen lujos y yo no", "codicia"),
    ("Siento que la felicidad se compra y me falta dinero", "codicia"),
    ("No me importa pisar a otros para subir", "codicia"),
    ("Me angustia no tener el mejor celular del mercado", "codicia"),
    ("Todo sería perfecto si tuviera más lana", "codicia"),
    ("Me siento vacío si no estreno ropa seguido", "codicia"),
    ("Odio conformarme con lo que tengo", "codicia"),
    ("Siempre quiero lo que tiene el vecino", "codicia"),
    ("Me obsesiona el estatus y la apariencia", "codicia"),
    ("No presto dinero a nadie, es mío", "codicia"),
    ("Siento que nunca voy a tener suficiente", "codicia"),
    ("Me da ansiedad ver que mi cuenta baja un poco", "codicia"),
    ("Quiero acumular propiedades y poder", "codicia"),
    ("Me molesta gastar en otros", "codicia"),
    ("Siento que la vida es una competencia de quién tiene más", "codicia"),
    ("Me frustra no poder pagar lujos innecesarios", "codicia"),
    ("Solo pienso en negocios y ganancias todo el día", "codicia"),
    ("Me siento miserable si no viajo en primera clase", "codicia"),
    ("Quiero todo para mí, no me gusta compartir", "codicia"),
    ("Me duele pagar precios altos, quiero todo gratis", "codicia"),
    ("Siento que el dinero es lo único que importa", "codicia"),
    ("Me comparo por las marcas que uso", "codicia"),
    ("No me satisface nada de lo que logro, quiero más", "codicia"),
    ("Me da envidia la gente rica y quiero ser ellos", "codicia"),
    ("Sacrifico mi tiempo libre por ganar extra", "codicia"),
    ("Me siento poderoso cuando gasto mucho", "codicia"),
    ("Tengo miedo de perder mi nivel de vida", "codicia"),
    ("Me obsesiona heredar o ganar la lotería", "codicia"),
    ("Siento que merezco más que los demás", "codicia"),
    ("Me da coraje ver gente con cosas que yo quiero", "codicia"),
    ("No regalo nada, todo me costó mucho", "codicia"),
    ("Quiero ser el más rico del cementerio", "codicia"),
    ("Me siento insatisfecho con mi sueldo siempre", "codicia"),
    ("Busco atajos para hacerme rico rápido", "codicia"),
    ("Me da igual la ética si hay dinero de por medio", "codicia"),
    ("Siento un hambre insaciable de posesiones", "codicia"),
    ("Me define lo que poseo, no lo que soy", "codicia"),
    ("Quiero acaparar todo lo que pueda", "codicia"),
    ("Me siento un fracasado si no tengo lujos", "codicia"),
    ("La ambición me consume por dentro", "codicia"),
    ("No disfruto lo que tengo por pensar en lo que me falta", "codicia"),
    ("Me siento esclavo de mis deseos materiales", "codicia"),
    ("El dinero es mi dios y mi dueño", "codicia"),
    
    
    # --- NUEVA EMOCIÓN: ABURRIMIENTO (Lote 11) ---
    ("Estoy muy aburrido, no sé qué hacer", "aburrimiento"),
    ("Qué hueva, todo me parece igual hoy", "aburrimiento"),
    ("Siento que los días son una copia exacta del anterior", "aburrimiento"),
    ("Nada me motiva, estoy apagado", "aburrimiento"),
    ("Me muero de aburrimiento en esta casa", "aburrimiento"),
    ("No encuentro nada interesante que ver o leer", "aburrimiento"),
    ("Siento que mi vida es una rutina gris", "aburrimiento"),
    ("Qué tedio, necesito algo nuevo ya", "aburrimiento"),
    ("Me aburre hasta mi propia compañía", "aburrimiento"),
    ("Estoy harto de hacer siempre lo mismo", "aburrimiento"),
    ("Siento que el tiempo pasa lentísimo cuando no hago nada", "aburrimiento"),
    ("Me da flojera hasta pensar", "aburrimiento"),
    ("No tengo ganas de nada, qué aburrido", "aburrimiento"),
    ("Me siento estancado en la monotonía", "aburrimiento"),
    ("Qué sopor, me estoy durmiendo de pie", "aburrimiento"),
    ("Busco emociones fuertes porque todo me aburre", "aburrimiento"),
    ("Siento que mi cerebro se está secando", "aburrimiento"),
    ("Nada me sorprende ya, qué triste", "aburrimiento"),
    ("Me la paso scrolleando el celular por puro aburrimiento", "aburrimiento"),
    ("Siento un vacío de actividades, no sé en qué ocuparme", "aburrimiento"),
    ("Me aburre la gente con la que hablo", "aburrimiento"),
    ("Quiero que pase algo, lo que sea, para romper esto", "aburrimiento"),
    ("Siento que estoy desperdiciando mi vida viendo el techo", "aburrimiento"),
    ("Qué fastidio, no hay planes divertidos", "aburrimiento"),
    ("Me siento como un zombi, sin chispa", "aburrimiento"),
    ("Me da pereza empezar algo nuevo", "aburrimiento"),
    ("Siento que ya vi todo lo que había que ver", "aburrimiento"),
    ("El aburrimiento me pone de mal humor", "aburrimiento"),
    ("No encuentro sentido a nada hoy, qué aburrido", "aburrimiento"),
    ("Me siento atrapado en un bucle infinito", "aburrimiento"),
    ("Qué lata, otra vez domingo sin hacer nada", "aburrimiento"),
    ("Me aburre mi trabajo, es siempre lo mismo", "aburrimiento"),
    ("Siento que necesito una aventura urgente", "aburrimiento"),
    ("Me cansa la misma música de siempre", "aburrimiento"),
    ("No soporto estar sin hacer nada productivo", "aburrimiento"),
    ("Me aburre estar solo conmigo mismo", "aburrimiento"),
    ("Siento que la vida pasa y yo estoy en pausa", "aburrimiento"),
    ("Qué mamera, todo es predecible", "aburrimiento"),
    ("Me siento apático, nada me llama la atención", "aburrimiento"),
    ("Me aburre la televisión, el internet, todo", "aburrimiento"),
    ("Siento que me falta adrenalina", "aburrimiento"),
    ("Qué aburrido es esperar sin hacer nada", "aburrimiento"),
    ("Me siento desconectado de la diversión", "aburrimiento"),
    ("Ya me cansé de estar acostado", "aburrimiento"),
    ("Me aburre la rutina de levantarme, trabajar y dormir", "aburrimiento"),
    ("Siento que no tengo hobbies que me llenen", "aburrimiento"),
    ("Qué pesadez, necesito un cambio de aires", "aburrimiento"),
    ("Me aburre escuchar las mismas historias", "aburrimiento"),
    ("Siento que me sobra tiempo y no sé usarlo", "aburrimiento"),
    ("Me da igual todo, estoy aburridísimo", "aburrimiento"),
    ("No hay reto que me estimule", "aburrimiento"),
    
    # --- NUEVA EMOCIÓN: NOSTALGIA (Lote 12) ---
    ("Extraño mucho cómo eran las cosas antes", "nostalgia"),
    ("Daría lo que fuera por volver a ser niño un día", "nostalgia"),
    ("Me acuerdo de esa época y se me encoge el corazón", "nostalgia"),
    ("Esos fueron los mejores años de mi vida", "nostalgia"),
    ("Siento que el tiempo pasó demasiado rápido", "nostalgia"),
    ("Me pone triste ver fotos viejas y ver cuánto cambiamos", "nostalgia"),
    ("Ojalá pudiera regresar a ese momento exacto", "nostalgia"),
    ("La música de antes era mucho mejor", "nostalgia"),
    ("Extraño la casa donde crecí", "nostalgia"),
    ("Me invade la nostalgia cuando huelo ese perfume", "nostalgia"),
    ("Antes todo era más sencillo y feliz", "nostalgia"),
    ("Me acuerdo de mis abuelos y los extraño tanto", "nostalgia"),
    ("Siento que dejé una parte de mí en el pasado", "nostalgia"),
    ("Quisiera revivir ese viaje una vez más", "nostalgia"),
    ("A veces lloro recordando viejos amigos", "nostalgia"),
    ("Me duele que esos días no volverán", "nostalgia"),
    ("Siento morriña de mi tierra", "nostalgia"),
    ("Me la paso pensando en el 'hubiera'", "nostalgia"),
    ("Extraño la inocencia que tenía antes", "nostalgia"),
    ("Ver esa película me trajo demasiados recuerdos", "nostalgia"),
    ("Siento que el presente no le llega ni a los talones al pasado", "nostalgia"),
    ("Me acuerdo cuando jugábamos en la calle sin preocupaciones", "nostalgia"),
    ("Extraño a mi ex, pero solo los buenos momentos", "nostalgia"),
    ("Me siento atrapado en mis recuerdos", "nostalgia"),
    ("Qué ganas de volver a la escuela y ver a todos", "nostalgia"),
    ("Esa canción me transporta a otro tiempo", "nostalgia"),
    ("Siento un vacío dulce al recordar mi primer amor", "nostalgia"),
    ("Me gustaría tener una máquina del tiempo", "nostalgia"),
    ("Extraño las comidas de mi mamá", "nostalgia"),
    ("Me da melancolía ver cómo han crecido mis hijos", "nostalgia"),
    ("Siento que fui más feliz ayer que hoy", "nostalgia"),
    ("Me acuerdo de las navidades de antes", "nostalgia"),
    ("Extraño la libertad de no tener responsabilidades", "nostalgia"),
    ("Me duele un poco el corazón de tanta memoria", "nostalgia"),
    ("Añoro los días de sol en ese lugar", "nostalgia"),
    ("Me siento viejo recordando esas modas", "nostalgia"),
    ("Extraño las cartas escritas a mano", "nostalgia"),
    ("Me acuerdo de cuando todo parecía posible", "nostalgia"),
    ("Siento que perdí algo valioso en el camino", "nostalgia"),
    ("Me da nostalgia pensar en mi perro de la infancia", "nostalgia"),
    ("Quisiera pausar el tiempo en ese instante", "nostalgia"),
    ("Extraño las risas con ese grupo de amigos", "nostalgia"),
    ("Me siento desconectado del ahora por pensar en el ayer", "nostalgia"),
    ("Todo cambió tanto y no me gusta", "nostalgia"),
    ("Me acuerdo de esa tarde de lluvia perfecta", "nostalgia"),
    ("Extraño sentir esa emoción de la primera vez", "nostalgia"),
    ("Me duele saber que esa etapa ya cerró", "nostalgia"),
    ("Siento nostalgia por vidas que no viví", "nostalgia"),
    ("Me acuerdo de los veranos interminables", "nostalgia"),
    ("Extraño quien yo era antes de que pasara todo esto", "nostalgia"),
    
    
    # --- NUEVA EMOCIÓN: DESESPERACIÓN (Lote 13) ---
    ("Ya no veo la luz al final del túnel", "desesperacion"),
    ("Siento que me estoy ahogando y nadie me ayuda", "desesperacion"),
    ("No tengo salida, estoy completamente atrapado", "desesperacion"),
    ("He perdido toda esperanza de que esto mejore", "desesperacion"),
    ("Me siento al borde del abismo", "desesperacion"),
    ("Ya no sé qué más hacer, lo he intentado todo", "desesperacion"),
    ("Siento que mi vida se desmorona pedazo a pedazo", "desesperacion"),
    ("Grito por ayuda pero nadie me escucha", "desesperacion"),
    ("Estoy en un pozo sin fondo", "desesperacion"),
    ("La oscuridad me está tragando vivo", "desesperacion"),
    ("Siento que voy a explotar si esto sigue así", "desesperacion"),
    ("No hay solución para mi problema, estoy condenado", "desesperacion"),
    ("Me siento desesperado, como un animal acorralado", "desesperacion"),
    ("Ya no tengo fuerzas para seguir luchando", "desesperacion"),
    ("Todo está perdido, no hay vuelta atrás", "desesperacion"),
    ("Siento una angustia que me quema por dentro", "desesperacion"),
    ("Estoy tocando fondo y no sé cómo subir", "desesperacion"),
    ("Me siento completamente desamparado", "desesperacion"),
    ("La desesperación no me deja respirar", "desesperacion"),
    ("Siento que el mundo se me viene encima", "desesperacion"),
    ("No veo futuro, solo dolor", "desesperacion"),
    ("Estoy en un callejón sin salida", "desesperacion"),
    ("Me siento impotente ante tanta desgracia", "desesperacion"),
    ("Ya no creo en nada, estoy roto", "desesperacion"),
    ("Siento que me voy a volver loco de la desesperación", "desesperacion"),
    ("Nadie entiende la gravedad de mi situación", "desesperacion"),
    ("Estoy perdiendo la cabeza, ayúdame por favor", "desesperacion"),
    ("Siento que estoy cayendo al vacío sin paracaídas", "desesperacion"),
    ("La vida me ha golpeado demasiado fuerte esta vez", "desesperacion"),
    ("No encuentro consuelo en nada ni en nadie", "desesperacion"),
    ("Siento que mi destino está sellado y es horrible", "desesperacion"),
    ("Estoy desesperado por una señal, una migaja de esperanza", "desesperacion"),
    ("Me siento como en una pesadilla de la que no despierto", "desesperacion"),
    ("Ya no aguanto ni un segundo más así", "desesperacion"),
    ("Siento que me arrancaron el alma", "desesperacion"),
    ("No hay escapatoria, estoy frito", "desesperacion"),
    ("Me siento condenado al fracaso eterno", "desesperacion"),
    ("La desesperación me tiene de rodillas", "desesperacion"),
    ("Siento que estoy luchando contra un tsunami con las manos", "desesperacion"),
    ("No veo ninguna opción viable, todas son malas", "desesperacion"),
    ("Me siento asfixiado por las circunstancias", "desesperacion"),
    ("Estoy en el punto de quiebre", "desesperacion"),
    ("Siento que ya no hay mañana para mí", "desesperacion"),
    ("La desesperación es un monstruo que me come", "desesperacion"),
    ("Estoy atrapado en un laberinto sin salida", "desesperacion"),
    ("Me siento naufrago en medio del océano", "desesperacion"),
    ("Ya no tengo lágrimas, solo desesperación seca", "desesperacion"),
    ("Siento que todo esfuerzo es inútil", "desesperacion"),
    ("Estoy viviendo un infierno en la tierra", "desesperacion"),
    ("Me siento completamente derrotado", "desesperacion"),
    
    # --- NUEVA EMOCIÓN: CELOS (Lote 14) ---
    ("Me molesta mucho que hable con él", "celos"),
    ("Siento que le importa más sus amigos que yo", "celos"),
    ("Por qué le dio like a esa foto", "celos"),
    ("Me hierve la sangre cuando la veo sonreírle a otro", "celos"),
    ("Tengo miedo de que encuentre a alguien mejor que yo", "celos"),
    ("Me siento amenazado cuando sale sin mí", "celos"),
    ("No soporto que mencione a su ex", "celos"),
    ("Me da rabia verlos tan juntos", "celos"),
    ("Siento que me está ocultando algo con esa persona", "celos"),
    ("Me pongo muy mal si no me contesta rápido y está en línea", "celos"),
    ("Por qué tiene que ser tan amable con todos", "celos"),
    ("Siento que sobro cuando está con sus compañeros", "celos"),
    ("Me da celos que comparta sus secretos con alguien más", "celos"),
    ("No quiero compartir su atención con nadie", "celos"),
    ("Me duele pensar que se divierte más sin mí", "celos"),
    ("Desconfío de sus intenciones con mi pareja", "celos"),
    ("Me siento inseguro cuando se arregla tanto para salir", "celos"),
    ("Odio que la miren tanto", "celos"),
    ("Me da coraje que prefiera estar allá que conmigo", "celos"),
    ("Siento que me están robando su cariño", "celos"),
    ("Me pone nervioso que tenga tantos amigos hombres", "celos"),
    ("No aguanto ver mensajes de desconocidos en su celular", "celos"),
    ("Me siento desplazado por su nuevo amigo", "celos"),
    ("Tengo celos hasta de su mascota a veces", "celos"),
    ("Me molesta que le dedique tiempo a otros", "celos"),
    ("Siento que pierdo mi lugar especial", "celos"),
    ("Me da rabia imaginarla con otro", "celos"),
    ("Por qué se ríe tanto con él", "celos"),
    ("Me siento posesivo y no puedo evitarlo", "celos"),
    ("Me da miedo que me cambien", "celos"),
    ("Siento una punzada en el estómago cuando los veo", "celos"),
    ("No me gusta que salga con ese grupo", "celos"),
    ("Me siento excluido de su mundo", "celos"),
    ("Me da celos que le cuente cosas a su mamá y no a mí", "celos"),
    ("Siento que compitó por su atención", "celos"),
    ("Me revienta que sea tan coqueto", "celos"),
    ("No confío en esa 'amiguita' suya", "celos"),
    ("Me siento inferior a la gente con la que sale", "celos"),
    ("Me da celos su pasado", "celos"),
    ("Odio sentirme así de inseguro", "celos"),
    ("Me molesta que abrace a otros", "celos"),
    ("Siento que cualquiera podría quitármelo", "celos"),
    ("Me da coraje que no me de mi lugar", "celos"),
    ("Me siento vigilante todo el tiempo", "celos"),
    ("Me da celos que tenga éxito y se aleje de mí", "celos"),
    ("Siento que soy la segunda opción", "celos"),
    ("Me pone mal pensar en dónde está y con quién", "celos"),
    ("Me da celos ver que es feliz lejos de mí", "celos"),
    ("Siento que me traicionan con la mirada", "celos"),
    ("No quiero que nadie más la toque", "celos"),
    
    # --- NUEVA EMOCIÓN: INSEGURIDAD (Lote 15) ---
    ("Siento que no soy suficiente para nada", "inseguridad"),
    ("Todos parecen saber lo que hacen menos yo", "inseguridad"),
    ("Tengo miedo de que descubran que soy un fraude", "inseguridad"),
    ("Me siento inferior a mis compañeros", "inseguridad"),
    ("Dudo de cada decisión que tomo", "inseguridad"),
    ("Siento que mi opinión no vale nada", "inseguridad"),
    ("Me da pánico hablar y decir una estupidez", "inseguridad"),
    ("No me siento capaz de lograr mis metas", "inseguridad"),
    ("Me comparo con los demás y siempre salgo perdiendo", "inseguridad"),
    ("Siento que no merezco estar donde estoy", "inseguridad"),
    ("Me siento feo y poco atractivo", "inseguridad"),
    ("Tengo miedo de que nadie me tome en serio", "inseguridad"),
    ("Necesito que me validen todo el tiempo para estar tranquilo", "inseguridad"),
    ("Siento que soy aburrido y nadie quiere estar conmigo", "inseguridad"),
    ("Me cuesta mucho confiar en mi propio criterio", "inseguridad"),
    ("Siento que soy un estorbo para los demás", "inseguridad"),
    ("Me da miedo intentar cosas nuevas por si fallo", "inseguridad"),
    ("Siento que todos me juzgan en secreto", "inseguridad"),
    ("No tengo talento, soy del montón", "inseguridad"),
    ("Me siento pequeño e insignificante", "inseguridad"),
    ("Tengo miedo de no estar a la altura de las expectativas", "inseguridad"),
    ("Me siento torpe socialmente", "inseguridad"),
    ("Siempre pienso que los demás se ríen de mí", "inseguridad"),
    ("No me gusta lo que veo en el espejo", "inseguridad"),
    ("Siento que no tengo nada interesante que ofrecer", "inseguridad"),
    ("Me paraliza el miedo a equivocarme", "inseguridad"),
    ("Siento que soy reemplazable fácilmente", "inseguridad"),
    ("Me da inseguridad mi futuro, no me veo capaz", "inseguridad"),
    ("Siento que molesto si hablo o pregunto", "inseguridad"),
    ("Pido perdón por todo, incluso por existir a veces", "inseguridad"),
    ("Me siento vulnerable y débil frente a los otros", "inseguridad"),
    ("No creo en mí mismo, la verdad", "inseguridad"),
    ("Siento que tengo muchos defectos y ninguna virtud", "inseguridad"),
    ("Me da miedo mostrarme como soy realmente", "inseguridad"),
    ("Siento que actúo un papel para agradar", "inseguridad"),
    ("Me siento menos inteligente que el resto", "inseguridad"),
    ("Tengo miedo al rechazo constante", "inseguridad"),
    ("Me saboteo porque no creo merecer el éxito", "inseguridad"),
    ("Siento que soy un error", "inseguridad"),
    ("Me cuesta horrores aceptar un cumplido, no me lo creo", "inseguridad"),
    ("Siento que voy a arruinarlo todo en cualquier momento", "inseguridad"),
    ("Me da inseguridad mi cuerpo y cómo me visto", "inseguridad"),
    ("Siento que no encajo en ningún grupo", "inseguridad"),
    ("Me siento invisible y sin voz", "inseguridad"),
    ("Tengo dudas constantes sobre si me quieren de verdad", "inseguridad"),
    ("Me siento defectuoso por dentro", "inseguridad"),
    ("Me da miedo tomar la iniciativa", "inseguridad"),
    ("Siento que todos avanzan y yo me quedo atrás por miedo", "inseguridad"),
    ("Me cuestiono todo lo que hago mil veces", "inseguridad"),
    ("Siento que no soy digno de cosas buenas", "inseguridad"),
    
    # --- NUEVA EMOCIÓN: DECEPCIÓN (Lote 16) ---
    ("Esperaba mucho más de ti, la verdad", "decepcion"),
    ("Me siento estúpido por haber creído en sus promesas", "decepcion"),
    ("Pensé que iba a ser diferente esta vez", "decepcion"),
    ("Qué desilusión tan grande me llevé", "decepcion"),
    ("Todo fue una mentira desde el principio", "decepcion"),
    ("Me duele ver que no eres quien yo creía", "decepcion"),
    ("Tanto esfuerzo para nada, qué decepción", "decepcion"),
    ("Confié ciegamente y me fallaron", "decepcion"),
    ("La realidad me golpeó muy duro, no es lo que soñé", "decepcion"),
    ("Siento que perdí el tiempo esperando algo que no pasó", "decepcion"),
    ("Me dejaste tirado cuando más te necesitaba", "decepcion"),
    ("No cumpliste tu palabra y eso duele", "decepcion"),
    ("Me siento defraudado por mi propia familia", "decepcion"),
    ("Creí que teníamos algo especial, pero me equivoqué", "decepcion"),
    ("Esta película de vida no tuvo el final feliz que quería", "decepcion"),
    ("Me decepciona mi propio rendimiento", "decepcion"),
    ("Esperaba apoyo y recibí indiferencia", "decepcion"),
    ("Se me cayó un ídolo hoy", "decepcion"),
    ("Siento un sabor amargo por cómo terminaron las cosas", "decepcion"),
    ("Me rompe el corazón que no les importara mi esfuerzo", "decepcion"),
    ("Pensé que habías cambiado, pero sigues igual", "decepcion"),
    ("Me siento engañado por la publicidad de la vida", "decepcion"),
    ("Qué triste ver la verdadera cara de la gente", "decepcion"),
    ("Me decepciona que no hayas luchado por mí", "decepcion"),
    ("Tenía las expectativas muy altas y me estrellé", "decepcion"),
    ("Siento que nada vale la pena si el resultado es este", "decepcion"),
    ("Me fallaste y no sé si pueda superarlo", "decepcion"),
    ("Qué desperdicio de talento y oportunidades", "decepcion"),
    ("Me siento vacío al ver que mi sueño era una farsa", "decepcion"),
    ("No eras quien yo pensaba, qué decepción", "decepcion"),
    ("Me duele haber apostado todo al caballo perdedor", "decepcion"),
    ("Siento que me vendieron humo", "decepcion"),
    ("Me decepciona la falta de compromiso de todos", "decepcion"),
    ("Creí en el sistema y me traicionó", "decepcion"),
    ("Me siento un tonto por haber tenido esperanza", "decepcion"),
    ("Qué bajón darse cuenta de la realidad", "decepcion"),
    ("Me decepciona no haber logrado mi meta", "decepcion"),
    ("Siento que me dieron la espalda", "decepcion"),
    ("Esperaba un 'gracias' y no recibí nada", "decepcion"),
    ("Me siento desilusionado del amor", "decepcion"),
    ("Qué feo es cuando se te cae la venda de los ojos", "decepcion"),
    ("Me decepciona ver en qué se convirtió este lugar", "decepcion"),
    ("Pensé que éramos un equipo", "decepcion"),
    ("Me duele que mis planes se desmoronaran así", "decepcion"),
    ("Siento que di perlas a los cerdos", "decepcion"),
    ("Me decepciona tu actitud infantil", "decepcion"),
    ("Esperaba madurez y encontré caprichos", "decepcion"),
    ("Siento que todo lo que construí fue de papel", "decepcion"),
    ("Me defraudaste profundamente", "decepcion"),
    ("Ya no espero nada de nadie para no decepcionarme", "decepcion"),
    ("Siento que la magia se rompió", "decepcion"),
    
    # --- NUEVA EMOCIÓN: APEGO (Lote 17) ---
    ("No puedo imaginar mi vida sin esa persona", "apego"),
    ("Me aferro a los recuerdos porque es lo único que me queda", "apego"),
    ("Tengo miedo de soltar y quedarme sin nada", "apego"),
    ("Por qué las cosas no pueden quedarse como están", "apego"),
    ("Siento que si lo dejo ir, me muero", "apego"),
    ("Necesito controlar todo para que no se vaya", "apego"),
    ("Me obsesiona perder lo que he construido", "apego"),
    ("Guardo cosas viejas que no uso por si acaso", "apego"),
    ("Siento que me arrancan un brazo si me quitan esto", "apego"),
    ("No quiero que nada cambie, nunca", "apego"),
    ("Me duele pensar en despedirme", "apego"),
    ("Siento que esa persona me pertenece", "apego"),
    ("No acepto que esta etapa se terminó", "apego"),
    ("Sigo revisando sus redes sociales, no puedo parar", "apego"),
    ("Me aferro a un trabajo que odio por seguridad", "apego"),
    ("Siento que mi identidad depende de esto", "apego"),
    ("No quiero tirar nada, todo tiene valor sentimental", "apego"),
    ("Me da pánico que mis hijos crezcan y se vayan", "apego"),
    ("Quiero congelar el tiempo aquí", "apego"),
    ("Siento que sin mi pareja no soy nada", "apego"),
    ("Me cuesta horrores cerrar ciclos", "apego"),
    ("Sigo esperando que vuelva aunque sé que no lo hará", "apego"),
    ("Me siento incompleto si no tengo eso conmigo", "apego"),
    ("Odio las despedidas, las evito a toda costa", "apego"),
    ("Me aferro a mi juventud y me duele envejecer", "apego"),
    ("Siento que necesito poseer para disfrutar", "apego"),
    ("No quiero compartirlo, es mío", "apego"),
    ("Me da ansiedad pensar en mudarme y dejar mi casa", "apego"),
    ("Sigo llorando por algo que pasó hace años", "apego"),
    ("Me aferro a tener la razón siempre", "apego"),
    ("Siento que si cambio, dejo de ser yo", "apego"),
    ("No puedo soltar el control de la situación", "apego"),
    ("Me obsesiona retener a la gente a mi lado", "apego"),
    ("Siento que mi felicidad depende de algo externo", "apego"),
    ("Me niego a aceptar la realidad tal como es", "apego"),
    ("Guardo rencor porque no quiero soltar el vínculo", "apego"),
    ("Me da miedo la libertad de no tener ataduras", "apego"),
    ("Siento que me defino por mis posesiones", "apego"),
    ("No puedo tirar esas cartas viejas", "apego"),
    ("Me aferro a la idea de lo que pudo ser", "apego"),
    ("Siento que perder esto es perder mi vida", "apego"),
    ("Me resisto a fluir con los cambios", "apego"),
    ("Quiero que me prometan que será para siempre", "apego"),
    ("Siento que me estoy agarrando de un clavo ardiendo", "apego"),
    ("No dejo ir mis viejas creencias limitantes", "apego"),
    ("Me aferro al dolor porque me conecta con el pasado", "apego"),
    ("Siento que necesito garantías de que no se irán", "apego"),
    ("Me cuesta adaptarme a lo nuevo", "apego"),
    ("Sigo yendo a los mismos lugares buscando fantasmas", "apego"),
    ("Me aferro a mi estatus social", "apego"),
    ("No quiero soltar el volante de mi vida", "apego"),
    ("Siento que todo debe ser eterno o no vale", "apego"),
    
    
    # --- NUEVA EMOCIÓN: AGOBIO (Lote 18) ---
    ("Tengo demasiadas cosas que hacer y no me da la vida", "agobio"),
    ("Siento que me falta el aire de tanta presión", "agobio"),
    ("Me están exigiendo por todos lados, ya no puedo más", "agobio"),
    ("Necesito un descanso urgente, estoy saturado", "agobio"),
    ("Todo se me juntó hoy, es demasiado", "agobio"),
    ("Siento que mi cabeza va a estallar", "agobio"),
    ("No sé por dónde empezar, es una montaña de pendientes", "agobio"),
    ("Me siento asfixiado por las responsabilidades", "agobio"),
    ("Quisiera desaparecer un rato y que nadie me hable", "agobio"),
    ("El estrés me está matando, en serio", "agobio"),
    ("Siento que estoy haciendo malabares y se me van a caer todos", "agobio"),
    ("No tengo ni un minuto para mí", "agobio"),
    ("Me siento acorralado por los problemas", "agobio"),
    ("Es demasiado ruido, demasiada gente, demasiado todo", "agobio"),
    ("Me pesa el cuerpo de tanto cansancio mental", "agobio"),
    ("Siento que todos quieren algo de mí ahora mismo", "agobio"),
    ("No puedo pensar con claridad, estoy bloqueado", "agobio"),
    ("Me da ansiedad ver mi lista de tareas", "agobio"),
    ("Siento que el tiempo se me escapa y no avanzo", "agobio"),
    ("Estoy al límite de mis fuerzas", "agobio"),
    ("Me siento culpable si descanso, pero estoy agotado", "agobio"),
    ("Todo es urgente, todo es para ayer", "agobio"),
    ("Siento una opresión en el pecho constante", "agobio"),
    ("Me siento pequeño ante tantos retos", "agobio"),
    ("Ya no disfruto nada por estar preocupado", "agobio"),
    ("Me siento como una olla a presión a punto de reventar", "agobio"),
    ("No puedo dormir pensando en todo lo que tengo que hacer", "agobio"),
    ("Siento que estoy corriendo en una rueda de hámster", "agobio"),
    ("Me agobia pensar en el futuro inmediato", "agobio"),
    ("Necesito que el mundo se detenga un momento", "agobio"),
    ("Siento que cargo con el peso del mundo en mis hombros", "agobio"),
    ("Me irrito por cualquier cosa de lo tenso que estoy", "agobio"),
    ("No veo cómo voy a lograr terminar todo esto", "agobio"),
    ("Me siento inundado de información", "agobio"),
    ("Quiero llorar de pura frustración y cansancio", "agobio"),
    ("Siento que no doy abasto", "agobio"),
    ("Me agobia tener que tomar tantas decisiones", "agobio"),
    ("Siento que me estoy quemando (burnout)", "agobio"),
    ("No tengo espacio mental para nada más", "agobio"),
    ("Me siento atrapado en mi propia vida", "agobio"),
    ("Es una carrera contra el reloj y voy perdiendo", "agobio"),
    ("Siento que me exigen perfección y no soy un robot", "agobio"),
    ("Me agobia la multitud y el ruido", "agobio"),
    ("Siento que estoy fallando en todo por querer hacer todo", "agobio"),
    ("Necesito simplificar mi vida, es un caos", "agobio"),
    ("Me siento devorado por las obligaciones", "agobio"),
    ("No puedo desconectar ni el fin de semana", "agobio"),
    ("Siento que mi batería está en 1% y no carga", "agobio"),
    ("Me agobia no tener el control", "agobio"),
    ("Siento que me estoy ahogando en un vaso de agua", "agobio"),
    
    # --- NUEVA EMOCIÓN: VACÍO (Lote 19) ---
    ("No siento nada, ni tristeza ni alegría, solo nada", "vacio"),
    ("Siento un hueco enorme en el pecho que no se llena", "vacio"),
    ("La vida no tiene sentido para mí", "vacio"),
    ("Me levanto por inercia, no porque quiera", "vacio"),
    ("Siento que soy un cascarón vacío", "vacio"),
    ("Nada me importa realmente, todo da igual", "vacio"),
    ("Miro al futuro y solo veo un espacio en blanco", "vacio"),
    ("Siento que mi alma se apagó", "vacio"),
    ("Estoy existiendo, pero no viviendo", "vacio"),
    ("Me siento desconectado de todo el mundo", "vacio"),
    ("Es como si estuviera muerto en vida", "vacio"),
    ("No tengo propósito, solo ocupo espacio", "vacio"),
    ("Siento una indiferencia total ante todo", "vacio"),
    ("Me pregunto para qué sirve todo esto y no hallo respuesta", "vacio"),
    ("Siento un silencio ensordecedor por dentro", "vacio"),
    ("Nada me llena, haga lo que haga", "vacio"),
    ("Me siento como un fantasma observando mi vida", "vacio"),
    ("He perdido la capacidad de sentir emoción", "vacio"),
    ("Todo me parece falso y sin sustancia", "vacio"),
    ("Siento que me falta una pieza fundamental", "vacio"),
    ("La comida no me sabe a nada, la vida tampoco", "vacio"),
    ("Me siento hueco, como si no hubiera nada adentro", "vacio"),
    ("No tengo metas, ni sueños, ni ganas", "vacio"),
    ("Siento que estoy flotando en la nada", "vacio"),
    ("Me da igual si es de día o de noche", "vacio"),
    ("Siento que mi risa es falsa, solo ruido", "vacio"),
    ("No encuentro mi lugar en el universo", "vacio"),
    ("Siento que soy invisible para mí mismo", "vacio"),
    ("La rutina me ha vaciado por completo", "vacio"),
    ("No hay pasión, no hay fuego, solo cenizas frías", "vacio"),
    ("Me siento ajeno a mi propio cuerpo", "vacio"),
    ("Siento que nada de lo que hago tiene impacto", "vacio"),
    ("Es un abismo interior que me asusta", "vacio"),
    ("Me siento anestesiado ante el dolor y el amor", "vacio"),
    ("Todo es gris, plano y sin sabor", "vacio"),
    ("Siento que se me olvidó cómo ser humano", "vacio"),
    ("No hay nada que me motive a seguir", "vacio"),
    ("Me siento como un robot cumpliendo funciones", "vacio"),
    ("El mundo sigue girando y a mí no me importa", "vacio"),
    ("Siento que estoy esperando el final sin prisa", "vacio"),
    ("No tengo nada que ofrecer y nada que pedir", "vacio"),
    ("Me siento vacante, deshabitado", "vacio"),
    ("La música ya no me hace sentir nada", "vacio"),
    ("Siento que soy un espectador aburrido de mi vida", "vacio"),
    ("No hay conexión con nada, estoy a la deriva", "vacio"),
    ("Siento que mi existencia es un error de cálculo", "vacio"),
    ("Me siento plano, sin altos ni bajos", "vacio"),
    ("Nada tiene color, todo es transparente", "vacio"),
    ("Siento que si desaparezco, no cambia nada", "vacio"),
    ("El vacío es tan grande que me consume", "vacio"),
    
    
    # --- NUEVA EMOCIÓN: EUFORIA (Lote 20) ---
    ("Me siento invencible, nada puede detenerme", "euforia"),
    ("Estoy tan feliz que podría explotar", "euforia"),
    ("Siento que soy el rey del mundo ahora mismo", "euforia"),
    ("Tengo una energía infinita, no puedo dormir", "euforia"),
    ("Todo es perfecto, maravilloso, increíble", "euforia"),
    ("Siento que voy volando, no toco el piso", "euforia"),
    ("Me quiero comer el mundo a mordidas ya", "euforia"),
    ("Nunca me había sentido tan vivo y poderoso", "euforia"),
    ("Siento electricidad corriendo por mis venas", "euforia"),
    ("Hoy es el mejor día de mi vida, sin duda", "euforia"),
    ("Me río de todo, la vida es un chiste buenísimo", "euforia"),
    ("Siento que puedo lograr lo imposible", "euforia"),
    ("Estoy en la cima y nadie me baja", "euforia"),
    ("Qué subidón de adrenalina tengo", "euforia"),
    ("Amo a todo el mundo, todos son geniales", "euforia"),
    ("Siento que brillo más que el sol", "euforia"),
    ("No hay límites para mí hoy", "euforia"),
    ("Estoy vibrando altísimo, es una locura", "euforia"),
    ("Me siento en éxtasis total", "euforia"),
    ("Todo me sale bien, tengo el toque de Midas", "euforia"),
    ("Quiero gritar de felicidad a los cuatro vientos", "euforia"),
    ("Siento que el universo conspira solo para mí", "euforia"),
    ("No puedo dejar de sonreír, me duele la cara", "euforia"),
    ("Estoy aceleradísimo, voy a mil por hora", "euforia"),
    ("Siento una dicha incontrolable", "euforia"),
    ("Soy imparable, una fuerza de la naturaleza", "euforia"),
    ("Qué maravilla estar vivo, todo es luz", "euforia"),
    ("Me siento borracho de felicidad sin beber nada", "euforia"),
    ("Tengo ganas de correr, saltar y bailar sin parar", "euforia"),
    ("Siento que gané la lotería de la vida", "euforia"),
    ("Mi confianza está por las nubes", "euforia"),
    ("Todo lo veo de colores brillantes", "euforia"),
    ("Siento que nada malo puede pasarme nunca más", "euforia"),
    ("Estoy en una nube rosa", "euforia"),
    ("Me siento superhéroe", "euforia"),
    ("Qué emoción tan grande, no quepo en mí", "euforia"),
    ("Siento que floto sobre los problemas", "euforia"),
    ("Estoy radiante, magnético", "euforia"),
    ("La vida es una fiesta eterna hoy", "euforia"),
    ("Me siento iluminado y genial", "euforia"),
    ("Tengo el corazón acelerado de pura emoción", "euforia"),
    ("Siento que toqué el cielo con las manos", "euforia"),
    ("Nadie puede arruinarme este momento", "euforia"),
    ("Estoy on fire, todo lo que toco es oro", "euforia"),
    ("Siento una gratitud explosiva y loca", "euforia"),
    ("Me siento más grande que mis problemas", "euforia"),
    ("Qué delirio de felicidad", "euforia"),
    ("Estoy fascinado con todo lo que veo", "euforia"),
    ("Siento que hoy empieza mi leyenda", "euforia"),
    ("Es demasiada alegría para un solo cuerpo", "euforia"),
]


# 2. LAS CITAS (Base de datos de sabiduría extendida)
# -----------------------------------------------------------------
# Aquí he fusionado todas las listas. Cada clave es ÚNICA y contiene
# TODAS las frases de todos los lotes mezcladas.
# -----------------------------------------------------------------
citas_db = {
    "tristeza": [
        "“El camino que puede ser nombrado no es el camino eterno.” — Tao Te Ching",
        "“La tristeza es como la lluvia; déjala caer, nutrirá las semillas de tu crecimiento.” — Proverbio Zen",
        "“Vacía tu mente de todo pensamiento. Deja que tu corazón esté en paz.” — Laozi",
        "“Incluso la noche más oscura terminará y el sol saldrá.” — Victor Hugo",
        "“La gran tierra me carga con un cuerpo, me hace trabajar con la vida y me da descanso en la muerte.” — Zhuangzi",
        "“Lo que la oruga llama el fin del mundo, el resto del mundo lo llama mariposa.” — Laozi",
        "“El dolor es inevitable, pero el sufrimiento es opcional.” — Proverbio Budista",
        "“No puedes evitar que las aves de la tristeza vuelen sobre tu cabeza, pero puedes evitar que aniden en tu cabello.” — Proverbio Chino",
        "“Todo lo que tiene un principio tiene un fin. Haz las paces con eso y todo estará bien.” — Jack Kornfield",
        "“El árbol que quiere tocar el cielo debe tener raíces que lleguen hasta el infierno.” — Carl Jung",
        "“La vida es un préstamo; la muerte es el regreso al origen. ¿Por qué estar triste por volver a casa?” — Liezi",
        "“Todo lo que nace vuelve a lo sin forma. Acepta el ciclo y el dolor se desvanecerá.” — Liezi",
        "“Suelta lo que crees que debes ser y abraza lo que eres.” — Brené Brown",
        "“El dolor es la ruptura del caparazón que encierra tu entendimiento.” — Kahlil Gibran",
        "“Si quieres conservar algo, debes admitir que puedes perderlo.” — Liezi",
        "“Si un bote vacío choca contra ti, no te enojas. Si hay alguien dentro, le gritas. Vacía tu bote (tu ego).” — Zhuangzi",
        "“La vida es una serie de cambios naturales. No te resistas a ellos, eso solo crea dolor.” — Laozi",
        "“Si un árbol cae en el bosque, se convierte en abono para el nuevo bosque. Tu caída también nutre tu futuro.” — Proverbio Zen",
        "“Lo que niegas te somete, lo que aceptas te transforma.” — Carl Jung"
    ],
    "ansiedad": [
        "“El hombre perfecto usa su mente como un espejo: no agarra nada, no rechaza nada.” — Zhuangzi",
        "“Si estás deprimido, vives en el pasado. Si estás ansioso, vives en el futuro. Si estás en paz, vives en el presente.” — Laozi",
        "“Preocúpate por lo que piensan los demás y siempre serás su prisionero.” — Laozi",
        "“La tensión es quien crees que deberías ser. La relajación es quien eres.” — Proverbio Chino",
        "“Quien pretende el dominio del mundo y mejorar este, se encamina al fracaso. El mundo es tan sagrado que no puede ser dominado.” — Tao Te Ching",
        "“El que camina a grandes zancadas no irá muy lejos.” — Laozi",
        "“Si no cambias la dirección, puedes terminar donde has comenzado.” — Laozi",
        "“No habites en el pasado, no sueñes con el futuro, concentra la mente en el momento presente.” — Buda",
        "“Tienes el poder sobre tu mente, no sobre los eventos externos. Date cuenta de esto y encontrarás fuerza.” — Marco Aurelio",
        "“El hombre que persigue dos conejos, no atrapa ninguno.” — Proverbio Chino",
        "“¿Tienes paciencia para esperar a que tu lodo se asiente y el agua se aclare?” — Tao Te Ching",
        "“No empujes el río, fluye solo.” — Barry Stevens",
        "“La preocupación no quita los problemas de mañana, solo quita la paz de hoy.” — Proverbio Zen",
        "“Si llenas tu casa de oro y jade, no podrás protegerla; el que acumula riqueza y honores siembra su propia desgracia.” — Tao Te Ching",
        "“Quien sabe que tiene suficiente es rico.” — Laozi",
        "“El que persigue la fama pierde su identidad; el que persigue la fortuna pierde su alma.” — Proverbio Chino",
        "“La felicidad no está en tener mucho, sino en necesitar poco.” — Liezi",
        "“Preocuparse es rezar por lo que no quieres.” — Proverbio Zen",
        "“La naturaleza no se apresura, y sin embargo todo se logra.” — Laozi",
        "“Si quieres enderezar lo curvo, primero debes dejar que se curve completamente.” — Tao Te Ching",
        "“El hombre que persigue la perfección camina hacia la decepción constante.” — Zhuangzi",
        "“Un viaje de mil millas comienza con un solo paso. No intentes saltarte el camino.” — Laozi",
        "“Preocuparse es como caminar con un paraguas abierto esperando a que llueva.” — Proverbio Zen"
    ],
    "calma": [
        "“La paz viene de dentro. No la busques fuera.” — Buda",
        "“El que está satisfecho con su parte es rico.” — Laozi",
        "“Al igual que una roca sólida no se mueve con el viento, los sabios no se inmutan por el elogio o la culpa.”",
        "“La naturaleza no se apresura, y sin embargo todo se logra.” — Laozi",
        "“El silencio es una fuente de gran fuerza.” — Laozi",
        "“Reposar es volver a su destino. Volver al destino es conocer la eternidad.” — Tao Te Ching",
        "“Sé como el agua: suave y flexible, pero capaz de erosionar la roca más dura.” — Laozi",
        "“Quédate sentado en silencio, sin hacer nada, y la primavera llega y la hierba crece sola.” — Proverbio Zen",
        "“La calma somete a lo agitado.” — Laozi",
        "“La respuesta más silenciosa es a veces la más ruidosa.”",
        "“El sabio no acumula. Cuanto más ayuda a los demás, más se beneficia él mismo.” — Laozi",
        "“La simplicidad es la máxima sofisticación.” — Laozi",
        "“Cuando bebes agua, recuerda la fuente.” — Proverbio Chino",
        "“El agua turbia se aclara dejándola quieta.” — Laozi",
        "“Sé como el bambú: cuanto más alto crece, más se inclina (humildad).” — Proverbio Chino",
        "“Cuando dejas de buscar aprobación, la encuentras.” — Tao Te Ching",
        "“La libertad suprema es no sentir la necesidad de explicar quién eres.”",
        "“Solo tengo tres tesoros que guardar: simplicidad, paciencia y compasión.” — Laozi",
        "“Sé como el agua: se adapta al recipiente sin perder su esencia.” — Tao Te Ching",
        "“La riqueza consiste en mucho más que tener oro; consiste en apreciar lo que ya tienes.” — Liezi",
        "“Quédate en el centro del círculo y deja que todas las cosas sigan su curso.” — Tao Te Ching"
    ],
    "ira": [
        "“El que domina a los otros es fuerte; el que se domina a sí mismo es poderoso.” — Tao Te Ching",
        "“Aferrarse a la ira es como beber veneno y esperar que la otra persona muera.” — Buda",
        "“La mejor respuesta a la ira es el silencio.”",
        "“Quien es capaz de dominarse a sí mismo cuando está enojado, ha vencido a su peor enemigo.”",
        "“La violencia, aunque bien intencionada, siempre rebota sobre uno mismo.” — Laozi",
        "“El buen hombre es el maestro del malo, y el mal hombre es la lección del buen hombre.” — Tao Te Ching",
        "“Lo suave y lo tierno vencen a lo duro y lo grosero.” — Laozi",
        "“Si alguien te ofrece un regalo (insulto) y tú no lo aceptas, ¿a quién pertenece el regalo?” — Buda",
        "“No te resistas, eso solo crea dolor. Deja que la realidad sea la realidad.” — Laozi",
        "“Es más fácil desviar el curso de un río que cambiar el carácter de un hombre necio. No te desgastes.” — Proverbio Chino",
        "“El que golpea primero admite que se le acabaron las ideas.” — Proverbio Chino",
        "“No hables si lo que vas a decir no es más hermoso que el silencio.”",
        "“Sé como el sándalo, que perfuma el hacha que lo hiere.” — Proverbio Hindú/Zen",
        "“El que se para de puntillas no se mantiene firme; el que se exhibe no brilla.” — Tao Te Ching",
        "“Nunca luches con un cerdo. Ambos se ensuciarán, pero al cerdo le gustará.” — George Bernard Shaw",
        "“La mejor venganza es no ser como tu enemigo.” — Marco Aurelio",
        "“El árbol que tiene las flores más bellas y los frutos más dulces es el primero al que le tiran piedras.” — Proverbio Oriental",
        "“Para conducir a la gente, camina detrás de ellos.” — Laozi",
        "“Responder a la ira con ira es como lanzar leña al fuego. Responder con silencio es quitarle el oxígeno.”",
        "“Si alguien te escupe, agradécele por limpiar tu cara. Si te insulta, agradécele por limpiar tu ego.” — Adaptación Zen"
    ],
    "confusion": [
        "“El barro fangoso se aclara si se deja reposar. La mente confusa se aclara si se deja en paz.”",
        "“No busques, no busques, no preguntes, no llames, no demandes. Relájate.” — Osho",
        "“El viaje de mil millas comienza con un solo paso.” — Laozi",
        "“Cuando el alumno está listo, el maestro aparece.”",
        "“Darte cuenta de que no entiendes es una virtud; no darte cuenta de que no entiendes es un defecto.” — Laozi",
        "“El que sabe, no habla; el que habla, no sabe.” — Tao Te Ching",
        "“Perfecto viajero es el que no sabe adónde va.” — Liezi",
        "“El sabio no enseña con palabras, sino con actos.” — Laozi",
        "“Solo los que conocen el valor de lo inútil pueden hablar de lo que es útil.” — Zhuangzi",
        "“Todos los hombres conocen la utilidad de lo útil, pero nadie conoce la utilidad de lo inútil.” — Zhuangzi",
        "“Cuando el ojo no está bloqueado, el resultado es la visión. Cuando la mente no está bloqueada, el resultado es la sabiduría.” — Proverbio Zen",
        "“La fama es el comienzo de la desgracia.” — Zhuangzi",
        "“Deja de pensar y termina con tus problemas.” — Laozi",
        "“El pez que se mantiene en aguas profundas no puede ser pescado; el hombre que guarda su misterio no puede ser manipulado.”",
        "“Conocer a otros es inteligencia; conocerse a sí mismo es verdadera sabiduría.” — Laozi",
        "“El sabio viaja todo el día sin dejar su propia casa.” — Laozi",
        "“No busques la verdad; solo deja de tener opiniones.” — Proverbio Zen",
        "“El conocimiento es aprender algo cada día. La sabiduría es soltar algo cada día.” — Proverbio Zen"
    ],
    "cansancio": [
        "“Aprende a descansar, no a renunciar.”",
        "“El arco que se mantiene siempre tenso, termina rompiéndose.”",
        "“Tomarse un descanso es parte del camino, no el final del mismo.”",
        "“Retirarse cuando la obra está hecha, ese es el camino del Cielo.” — Tao Te Ching",
        "“Correr siete veces y sentarse una vez.” — Proverbio Zen",
        "“Parar al menos una vez cada día para mirarte a ti mismo.” — Proverbio Chino",
        "“Haz las cosas difíciles mientras son fáciles y haz las grandes cosas mientras son pequeñas.” — Laozi",
        "“Nadar contra la corriente agota; flotar con ella renueva.” — Principio Wu Wei",
        "“El hombre que mueve montañas empieza apartando piedrecitas.” — Confucio",
        "“No hay mayor delito que la codicia; no hay mayor desgracia que no saber contentarse.” — Laozi",
        "“Una vela no pierde su luz por compartirla con otra, pero se consume si arde demasiado rápido.”",
        "“No te rindas, descansa. El campo que descansa da mejor cosecha.” — Proverbio Chino",
        "“Incluso el río más caudaloso necesita una llanura para calmarse.”",
        "“Hacer nada es mejor que estar ocupado haciendo nada.” — Laozi"
    ]
}